Workflow
itberries/Technopark-WPI-2019-frontend pull request #9
Opened 2019-03-11 11:52 UTC by Rikud

Все элементы LearnMap представляют собой компоненты, а именно:

- LearnMapRow - сущность "строки" learnMap
- LearnMapPoints - точечный элемент, кушает на вход 1 параметр "position" задающий положение точек (1-5)
- LearnMapSubsection - кнопка перехода на подсекцию, принимает параметры "text" - текст кнопки, ;"start" - в какой части строки начинается кнопка, "end" -  в какой части заканчивается.;
- LearnMapSeparator - разделитель, принимает 1 параметр "text" - текст рядом с разделителем;

Все компоненты хранятся в своих папочках с уникальными для них стилями

2019-03-11 19:47 UTC, puchninanastya requested changes

2019-03-11 19:47 UTC, puchninanastya commented on src/App.js
> +    window.scrollTo(0, document.getElementsByClassName('learnMap')[0].scrollHeight);
Вань, а у тебя в итоге работает скрол вниз при запуске этой панели? У меня нет

2019-03-11 19:47 UTC, puchninanastya commented on src/App.js
> +    window.scrollTo(0, document.getElementsByClassName('learnMap')[0].scrollHeight);
А зачем scrollTo в и App и в LearnMap

2019-03-11 19:47 UTC, puchninanastya commented on src/panels/workflow/learnMap/learnMap.css
> +.learnMap__col_pos_2 {
Вань, давай заменим это на [CSS-in-JS](https://reactjs.org/docs/faq-styling.html). Для таких динамических стилей.

2019-03-11 19:47 UTC, puchninanastya commented on src/panels/workflow/Workflow.js
> +import LearnMap from './learnMap/learnMap';
Переименовываю в LearningMap, так как не ИзучатьКарту, а УчебнаяКарта/КартаОбучения

2019-03-11 19:47 UTC, puchninanastya commented on src/panels/workflow/learnMap/learnMap.js
> +          <LearnMapRow>
Попробуем динамически сгенерировать этот список компонентов?

2019-03-11 20:15 UTC, puchninanastya commented on .eslintrc.json
> +        "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }]
Вань, давай без циклом с ++, может?) есть поудобнее все-таки методы

2019-03-11 21:32 UTC, puchninanastya commented on src/panels/Workflow/LearningMap/__Separator/LearningMap__Separator.scss
> +  font-size: 3vh;
вроде бы не очень хорошо в vh задавать размер шрифта, никак не увеличивается размер если делать cmd+ (увеличение в браузере).

2019-03-11 22:32 UTC, puchninanastya commented on src/panels/Workflow/LearningMap/__Points/LearningMap__Points.js
> +    const positionClass = props.position === '' ? '' : `learningMap__col_pos_${props.position}`;
вот такие манипуляции вроде не обязательны) так как мы пишем в дефолтПропс значения по-умолчанию)

2019-03-11 23:43 UTC, puchninanastya commented on src/App.js
> +    window.scrollTo(0, document.getElementsByClassName('learnMap')[0].scrollHeight);
и из-за этого падает, если перейти через браузер не на /workflow урлу.

2019-03-11 23:43 UTC, puchninanastya commented on src/panels/workflow/learnMap/learnMap.css
> +.learnMap__col_pos_2 {
но это не точно

2019-03-11 23:44 UTC, puchninanastya commented on src/panels/workflow/learnMap/learnMap.js
> +          <LearnMapRow>
Пока обновила под структуру и стили как в прототипе

2019-03-11 23:44 UTC, puchninanastya commented on .eslintrc.json
> +        "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }]
но это не точно

2019-03-11 23:45 UTC, puchninanastya commented on src/panels/Workflow/LearningMap/__Separator/LearningMap__Separator.scss
> +  font-size: 3vh;
поменяла на em 🙈

2019-03-11 23:45 UTC, puchninanastya commented on src/panels/Workflow/LearningMap/__Points/LearningMap__Points.js
> +    const positionClass = props.position === '' ? '' : `learningMap__col_pos_${props.position}`;
убрала 🌝

2019-03-11 23:49 UTC, puchninanastya commented
Вань, переделала стили под scss, чуть пофиксила некоторые места в js и jsx компонентов.
Добавила isActive, isCurrent стили по пропсам. 
isCompleted добавила, но не реализовала. Это галочка в зеленом полигоне (см. прототип), надо делать с отдельным элементом, наверное, и с position абсолют позиционировать относительно кнопки. И с добавлением ракеты на isActive тоже самое (и тоже не делала).

Если ты по коду все одобряешь, смогу утром порезолвить конфликтики и мержить.
Если нет, то пофиксь, где не согласен:)

2019-03-12 05:52 UTC, Rikud commented on src/App.js
> +    window.scrollTo(0, document.getElementsByClassName('learnMap')[0].scrollHeight);
В App я пытался заставить его скролить при первой загрузке, но чет он уперся и не хочет этого делать. При перезагрузке странички он почему то восстанавливает ту позицию, которая была перед обновлением страницы

2019-03-12 06:26 UTC, Rikud commented on src/panels/workflow/learnMap/learnMap.css
> +.learnMap__col_pos_2 {
Давай. Посмотри тут какой вариант тебе больше нравиться:
https://css-live.ru/articles/vsyo-chto-vam-nuzhno-znat-o-css-in-js.html

2019-03-12 06:46 UTC, Rikud commented on .eslintrc.json
> +        "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }]
Давай. А как можно по-другому организовать цикл повторяющийся n раз? Например вот тут нужно создать 3 одинаковых точки.
https://github.com/itberries/Technopark-WPI-2019-frontend/blob/61b5315a04fb77239559323ef9923adee32e1cc5/src/panels/Workflow/LearningMap/__Points/LearningMap__Points.js#L32-L38

2019-03-12 06:48 UTC, Rikud commented on src/panels/Workflow/LearningMap/__Separator/LearningMap__Separator.scss
> +  font-size: 3vh;
Да, хорошая идея

2019-03-12 06:51 UTC, Rikud commented on src/panels/Workflow/LearningMap/__Points/LearningMap__Points.js
> +    const positionClass = props.position === '' ? '' : `learningMap__col_pos_${props.position}`;
Тогда нужно передавать в конструктор "learningMap__col_pos_1" вместо простого "1". Если сделаем css in js то такие манипуляции будут не нужны.

2019-03-12 06:53 UTC, Rikud commented
isActive, isCurrent это у тебя в ветке или ты в эту добавила?

2019-03-12 08:21 UTC, puchninanastya approved these changes

2019-03-12 08:29 UTC, merged